### ISSUE TITLE
improved drain life talent

### ISSUE THREAD

**Issue by SnowyNoS** [NostraliaWoW/mangoszero#122]
when ever i put a point on improved drain life damage does not increase please fix thanks :(

Post.
http://nostralia.org/forums/viewtopic.php?f=15&t=81

**Comment by pjfry651** [comment]
Should be closed with commit 23ec359.

Example: 1 rank into Imp Drain Life increases Drain Life by 2%, meaning Rank 1 Drain Life should drain 10.2 damage per tick. Because WoW doesn't support fractional damage, it instead makes the spell read "drains 10 - 11 life per tick". Previously, the spell would still tick only for the lower amount, in this case, 10.

After this commit, the spell will tick randomly for 10 or 11 damage.

**Comment by pjfry651** [comment]
The effect can be seen in this video https://youtu.be/dtYXN9bMV2c?t=53s
