### ISSUE TITLE
Rogue Distract causing mobs to aggro stealthed players even when they're facing other way

### ISSUE THREAD

**Issue by Nostralia** [NostraliaWoW/mangoszero#203]
https://www.youtube.com/watch?v=TlUo8-LsSVg     <-- With Distract
https://www.youtube.com/watch?v=AWR1CBfiimU    <-- Without Distract

**Comment by sundayz** [comment]
Could not reproduce. Possibly fixed in 29a3e38.

**Comment by sundayz** [comment]
Related to #126.

**Comment by SnowyNoS** [comment]
I will ask the rogue player base for there feedback on this. I think it would be a great idea to get info from them if the information is veiled.

**Comment by SnowyNoS** [comment]
Distract still seems to be doing the same thing for me. 

I use it on a mob to turn them around so that I can attack from behind and before I get to them or attack the mob turns around and hits me.
And sometimes it says that I need to be behind the target when I already am.
So I think it may only be a visual thing.

**Comment by natrist** [comment]
Closed as duplicate of #126
