### ISSUE TITLE
Bannok Grimaxe - also re-spawns in 1 hour

### ISSUE THREAD

**Issue by SnowyNoS** [NostraliaWoW/mangoszero#216]
This boss also has a fast re-spawn timer.

NPC 
http://db.vanillagaming.org/?npc=9596

**Comment by sundayz** [comment]
Fixed in https://github.com/NostraliaWoW/database/commit/c32d2793e1b7542e6ea3268834bca922fbf9024c.

**Comment by SnowyNoS** [comment]
This is a dumb question maybe but don't bosses only re-spawn after the insistence is reset by the player?

**Comment by sundayz** [comment]
Not supported by the core, as the maximum respawn time is 7 days.

In raids, they respawn after 7 days because at that point it's the same as resetting and clearing the raid again.

For heroics it's 24 hours because that's how long it would've taken for the dungeon lock to expire, so you can't cheat and get around the lock period by AFKing in the instance and waiting for respawn.

**Comment by SnowyNoS** [comment]
Very good thx
