### ISSUE TITLE
Missing Melee Leeway Mechanic

### ISSUE THREAD

**Issue by SnowyNoS** [NostraliaWoW/mangoszero#268]
name: general pvp
summary, there is a fairly srs sort of a bug going on with pvp, or dueling. its hard to pinpoint exactly what it is, but when 2 melee classes are fighting it is as though both have 300 ping, constant too far away, facing wrong way etc errors, ill run around someone, facing them spamming gouge and it will take 5-10 hits of gouge before it goes off, same happens with auto attacks and other abilities.

steps to reproduce, have 2 melee do a high pased duel 

SS/vid dont have any.

reported by thetabop

extra info. dont really have any, it shouldnt be this way. and it makes dueling / pvp for 2 melees practically impossible if it is done at any remote skill level.

further info, i was dueling rock, he had 3 ping, i have 34. it took me maybe 10 sec to open on him with cheapshot, even tho i was right next to him in stealth spamming cheapshot it wouldnt go off, and he said basically he cant even hit me, it is just like we have 300 ping each.but dont.

post,
https://nostralia.org/forums/viewtopic.php?f=28&t=321

**Comment by sundayz** [comment]
@pjfry651 

When both targets are at > 70% of normal movement speed, 2.5 yards is added to your melee spells, accounting for lag due to movement extrapolation in client. We are missing this mechanic on the serverside, which is why players may find it difficult to hit other moving targets during melee combat.

Source: https://elysium-project.org/bugtracker/issue/2307
