### ISSUE TITLE
Quest turn in format for multiple give-ins incorrect

### ISSUE THREAD

**Issue by Nostralia** [NostraliaWoW/mangoszero#57]
When turning in a quest if one quest turn in is offered, the quest Format still request you click on the? to turn in the quest. While on Nostalrius clicking the NPC directs you straight to the quest completion format.  Source:  Nostralia: https://puu.sh/thvBq/e7e3e2cd6a.png /// Nostalrius: https://puu.sh/thvB9/7b0ae05b82.png

**Comment by natrist** [comment]
So, if only one quest is offered, it should be displayed right away?

**Comment by Nostralia** [comment]
Yes -

**Comment by natrist** [comment]
The issue here is the NPC flag not being set properly:
If the gossip flag (0x1) is set, the NPC will display a list of all available quests (even if only one).
The NPC will however display the quest offer if it is flagged as a quest giver (0x2).

The aforementioned example has been fixed as of DB commit [a4562a](https://github.com/NostraliaWoW/database/commit/a4562a819f7a07ceba71886909ea70155721e660)
